### PR TITLE
search_functionality

### PR DESCRIPTION
**Pull request by surajgajul**
Changes done:

INCF Portal - Brave 6_6_2024 10_40_20 PM

INCF Portal - Brave 6_6_2024 10_40_50 PM

https://incf-impactviz.atlassian.net/browse/GSOC-1?atlOrigin=eyJpIjoiZDk0MjM1OWMwMDIwNDRiOGIxOTk5Njc0MWU0YWI1YTgiLCJwIjoiaiJ9

### CODE REVIEW

**Comment by atharva434** [comment]
Hi can you please specify what utils.py and utilss.py is doing as in name it appropriately.
Thanks.

**Comment by atharva434** [comment]
Also can you hide the id and score its not really required in UI i believe.

**Comment by surajgajul** [comment]
Follow up story, domain based, sub domain based and tech stack based searching

**Comment by atharva434** [comment]
Looks good now. Great work!

**Pull request merged**
